DROP TABLE IF EXISTS import.master_people;
DROP TABLE IF EXISTS import.master_buildings;
DROP TABLE IF EXISTS import.master_properties;
DROP TABLE IF EXISTS import.master_providers;
DROP TABLE IF EXISTS import.master_incidences;
DROP TABLE IF EXISTS import.master_announces;
DROP TABLE IF EXISTS import.master_bank_accounts;
DROP TABLE IF EXISTS import.master_banking_transactions;
DROP SCHEMA IF EXISTS import;

DROP TABLE IF EXISTS community_fees CASCADE;
DROP TABLE IF EXISTS banking_transactions CASCADE;
DROP TABLE IF EXISTS bank_accounts CASCADE;
DROP TABLE IF EXISTS neighbors_to_properties CASCADE;
DROP TABLE IF EXISTS owners_to_properties CASCADE;
DROP TABLE IF EXISTS incidences CASCADE;
DROP TABLE IF EXISTS properties CASCADE;
DROP TABLE IF EXISTS announces CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS buildings CASCADE;
DROP TABLE IF EXISTS providers CASCADE;
DROP TABLE IF EXISTS people CASCADE;
